name: fenv_graphql_core
description: >-
  Runtime library providing core functionality for fenv GraphQL code generation,
  including query runners and state management.
version: 0.0.0
repository: https://github.com/fenv-org/fenv_graphql_codegen
topics:
  - graphql
  - state-management
  - flutter
  - hooks
  - pagination

environment:
  sdk: ^3.9.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
