name: blog_platform_test
description: Test package for fenv_graphql_codegen integration tests
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  fenv_graphql_core: ^0.2.0
  flutter_hooks: ^0.21.3+1
  gql: ^1.0.1
  graphql: ^5.2.2
  graphql_flutter: ^5.2.0
  hooks_riverpod: ^3.0.2
  http: ^1.5.0
  meta: ^1.16.0

dev_dependencies:
  build_runner: ^2.7.0
  fenv_graphql_codegen:
    path: ../../fenv_graphql_codegen/
  fenv_graphql_test: ^0.2.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
