name: fenv_graphql_test
description: >-
  Testing utilities and mock implementations for GraphQL operations generated
  by fenv_graphql_codegen.
version: 0.1.0
repository: https://github.com/fenv-org/fenv_graphql_codegen
topics:
  - graphql
  - testing
  - mocking
  - test-utilities

environment:
  sdk: ^3.9.0

dependencies:
  barrel_files_annotation: ^0.2.0
  fenv_graphql_core: ^0.1.0
  flutter:
    sdk: flutter
  graphql: ^5.2.2
  graphql_flutter: ^5.2.0

dev_dependencies:
  barrel_files: ^0.2.0
  build_runner: ^2.5.4
  flutter_test:
    sdk: flutter
  lints: ^6.0.0
