name: fenv_graphql_test
description: >-
  Testing utilities and mock implementations for GraphQL operations generated
  by fenv_graphql_codegen.
version: 0.0.0
repository: https://github.com/fenv-org/fenv_graphql_codegen
topics:
  - graphql
  - testing
  - mocking
  - test-utilities

environment:
  sdk: ^3.9.0

# Add regular dependencies here.
dependencies:
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
