name: Publish fenv_graphql_test to pub.dev

on:
  push:
    tags:
      - 'fenv_graphql_test-v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish:
    permissions:
      id-token: write # Required for authentication using OIDC
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
    with:
      working-directory: fenv_graphql_test
