name: fenv_graphql_codegen
description: >-
  A Dart code generator that creates test-friendly wrappers and mock
  implementations for GraphQL operations.
version: 0.0.0+3
repository: https://github.com/fenv-org/fenv_graphql_codegen
topics:
  - graphql
  - codegen
  - testing
  - code-generator
  - mocking

environment:
  sdk: ^3.9.0

dependencies:
  analyzer: ^7.6.0
  build: ^2.5.4
  build_config: ^1.1.1
  dart_style: ^3.1.0
  graphql_codegen: ^1.2.4

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
