name: fenv_graphql_codegen
description: >-
  A Dart code generator that creates test-friendly wrappers and mock
  implementations for GraphQL operations.
version: 0.1.0
repository: https://github.com/fenv-org/fenv_graphql_codegen
topics:
  - graphql
  - codegen
  - testing
  - code-generator
  - mocking

environment:
  sdk: ^3.9.0

dependencies:
  analyzer: ^8.1.1
  build: ^4.0.2
  build_config: ^1.2.0
  dart_style: ^3.1.2
  graphql_codegen: ^3.0.0

dev_dependencies:
  lints: ^6.0.0
  path: ^1.9.1
  test: ^1.24.0
