name: fenv_graphql_codegen
description: >-
  A Dart code generator that creates test-friendly wrappers and mock
  implementations for GraphQL operations.
version: 0.0.0+3
repository: https://github.com/fenv-org/fenv_graphql_codegen
topics:
  - graphql
  - codegen
  - testing
  - code-generator
  - mocking

environment:
  sdk: ^3.9.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
